export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};

// This is your root layout component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* This is where the header/footer will be */}
        <header>My Header</header>
        <main>{children}</main> {/* Pages will be rendered here */}
        <footer>My Footer</footer>
      </body>
    </html>
  );
}
